title: Hello
author: Vishant
email: agarwalvishant8@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Hello! How are you?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
